# Generated by Django 3.2.7 on 2021-10-09 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20211009_1346'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
